name: 'retail_semantic_layer'
version: '1.0.0'
config-version: 2

profile: 'retail_semantic_layer'

# File paths
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Model configuration
models:
  retail_semantic_layer:

    # STAGING MODELS
    # Light transformations, 1:1 with sources
    staging:
      +materialized: view


    # MART MODELS
    # Business logic, facts & dimensions
    marts:
      +materialized: table


    # SEMANTIC EXPOSURE LAYER
    # Public-facing views
    semantic:
      +materialized: view
      +schema: public_demo
